apiVersion: v1
kind: Pod
metadata:
  name: svc-dns-pod
  namespace: service-namespace
  labels:
    name: svc-dns-pod
spec:
  containers:
  - name: alpine-dns
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
        apk update && apk add --no-cache curl && sleep 3600
