apiVersion: v1
kind: Pod
metadata:
  name: configmap-posix-demo-pod
spec:
  containers:
    - name: configmap-posix
      image: jakirbd/my-node-server
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: player-posix-demo-pod