apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: my-pod-label
    tier: frontend
spec:
  containers:
    - name: frontend-container
      image: nginx
      ports:
        - containerPort: 8080
