apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: Um9vdEAwNTQwMDM=     # base64 of 'Root@054003'
  username: amFraXI=                  # base64 of 'jakir'
  user-password: U3FsQDA1NDAwMw==     # base64 of 'Sql@054003'
  database: c2hhcmVkdmRi              # base64 of 'sharedvdb'
