apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
        - name: curl-installer
          image: alpine:latest