apiVersion: v1
kind: Pod
metadata:
  name: svc-test-pod
  labels:
    name: svc-test-pod
spec:
  containers:
  - name: alpine-test
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
        apk update && apk add --no-cache curl && sleep 3600
