apiVersion: v1
kind: Pod
metadata:
  name: liveness-http-probe
  labels:
    name: liveness-http-probe
spec:
  containers:
    - name: liveness-http-probe-nginx
      image: nginx:latest
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
